export const WorkoutActionTypes = {
  ADD_EXERCISE: "ADD_EXERCISE",
  REMOVE_EXERCISE: "REMOVE_EXERCISE",
  SET_EXERCISE_NAME: "SET_EXERCISE_NAME",
  FETCH_EXERCISES_START: "FETCH_EXERCISES_START",
  FETCH_EXERCISES_SUCCESS: "FETCH_EXERCISES_SUCCESS",
  FETCH_EXERCISES_FAILURE: "FETCH_EXERCISES_FAILURE",
  ADD_SET: "ADD_SET",
  REMOVE_SET: "REMOVE_SET",
  SET_REPS: "SET_REPS",
  SET_WEIGHT: "SET_WEIGHT",
  SET_PLAN : "SET_PLAN"
};
