export const ExerciseActionTypes = {
  CHECKIN_EXERCISE: "CHECKIN_EXERCISE",
  ADD_SET: "ADD_SET",
  REMOVE_SET: "REMOVE_SET",
  ADD_EXERCISE: "ADD_EXERCISE",
  REMOVE_EXERCISE: "REMOVE_EXERCISE",
  SET_EXERCISE_NAME: "SET_EXERCISE_NAME",
  OPEN_EXERCISE: "OPEN_EXERCISE",
  FETCH_EXERCISES_START: "FETCH_EXERCISES_START",
  FETCH_EXERCISES_SUCCESS: "FETCH_EXERCISES_SUCCESS",
  FETCH_EXERCISES_FAILURE: "FETCH_EXERCISES_FAILURE",
};
