export const ExerciseActionTypes = {
  CHECKIN_EXERCISE: "CHECKIN_EXERCISE",
  ADD_SET: "ADD_SET",
  REMOVE_SET: "REMOVE_SET",
  ADD_EXERCISE: "ADD_EXERCISE",
  REMOVE_EXERCISE: "REMOVE_EXERCISE",
  SET_EXERCISE_NAME: "SET_EXERCISE_NAME"
};
