export const TrainingdayActionTypes = {
  FETCH_TRAININGDAY_START: "FETCH_TRAININGDAY_START",
  FETCH_TRAININGDAY_SUCCESS: "FETCH_TRAININGDAY_SUCCESS",
  FETCH_TRAININGDAY_FAILURE: "FETCH_TRAININGDAY_FAILURE"
};
