export const SetsActionTypes = {
  CHECKIN_SETS: "CHECKIN_SETS",
  ADD_SET: "ADD_SET",
  REMOVE_SET: "REMOVE_SET",
  SET_WEIGHT: "SET_WEIGHT",
  SET_REPS: "SET_REPS",
  FETCH_SETS_START: "FETCH_SETS_START",
  FETCH_SETS_SUCCESS: "FETCH_SETS_SUCCESS",
  FETCH_SETS_FAILURE: "FETCH_SETS_FAILURE"
};
